site_name: FPSim2
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Getting started:
    - Installation: user_guide/install.md
    - Creating FP Database: user_guide/create_db_file.md
  - CPU searches:
    - Similarity Search: user_guide/similarity.md
    - Tversky Search: user_guide/tversky.md
    - Substructure Screenout: user_guide/subs_screenout.md
    - Similarity Matrix: user_guide/sim_matrix.md
  - GPU searches:
    - GPU Similarity Search: user_guide/gpu.md
  - Contrib:
    - iSIM: user_guide/contrib.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/chembl/FPSim2
repo_name: chembl/FPSim2
