package:
  name: fpsim2
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/chembl/FPSim2

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - rdkit
  run:
    - python
    - pytables
    - sqlalchemy
    - rdkit

test:
  imports:
    - FPSim2

about:
  home: https://github.com/chembl/FPSim2
  license: MIT
  license_file: LICENSE