package:
  name: fpsim2
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11
  run:
    - python
    - numpy>=1.14
    - pytables>=3.4.4
    - rdkit>=2018.09
    - scipy
    - tqdm
    - vs2015_runtime  # [win]

test:
  imports:
    - FPSim2

about:
  home: https://github.com/chembl/FPSim2
  license: MIT
  license_file: LICENSE