name: Deploy MkDocs
on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - run: pip install mkdocs mkdocs-material "mkdocstrings[python]" mkdocs-gen-files
      
      - run: mkdocs gh-deploy --force