name: FPSim2 MySQL tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - '*'
    tags: '*'

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: python:3.10-bullseye

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mysql
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest mysqlclient
          pip install -e .

      - name: Run MySQL tests
        run: |
          pytest
